### PR TITLE
Add support for disconnected systems.

### PR DESCRIPTION
**Pull request by jeffmcutter**
In addition to CDN, also support both disconnected Satellite and custom repositories.

### CODE REVIEW

**Review by andywaltlova — COMMENTED** [review]
LGTM, do we need to bump collection version in galaxy.yml? or is that taken care of in some automation?

**Review by r0x0d — APPROVED** [review]
Hi, @jeffmcutter! 

Thanks for your first PR. It looks great. I will merge it as soon as possible.

**Comment by r0x0d** [comment]
> LGTM, do we need to bump collection version in galaxy.yml? or is that taken care of in some automation?

Let's bump the version in another PR, but only when we will do a new release. @jeffmcutter, is this something that you need right away to be available in galaxy/automation hub?

**Comment by jeffmcutter** [comment]
@r0x0d I do not need it right away, but I anticipate I will need it later this year.  I have a couple more PR's I'm working on also, so maybe wait for those. :-)

**Comment by r0x0d** [comment]
> @r0x0d I do not need it right away, but I anticipate I will need it later this year. I have a couple more PR's I'm working on also, so maybe wait for those. :-)

That's a deal, then! I don't remember any specific work from our side that needs to be pushed to production right away, so I think we will wait for a new build once your PRs are all merged. 

By that time, @jeffmcutter, you could either say in a comment in the PR that your changes are ready to go to prod, or either ping me in slack. (@ rolivier)

**Pull request merged**
